### ISSUE TITLE
Consumer Data Sharing not running in browser

### ISSUE THREAD

**Issue by markchan-gits** [ConsumerDataRight/mock-data-recipient#26]
**Describe the bug**
Unable to retrieve data via Consumer Data Sharing on banking resource api’s that have valid consents.
(Ie the /data-sharing/proxy) injection is not working in browser.

However successfully hit the mock data holder endpoint using mtls and access tokens via postman on get banking/accounts.

**To Reproduce**
1. Successfully pulled and composed docker container with all three mocks as per default config and data
2. Successfully navigated to mock adr url and performed the below actions
3. Successfully executed Discovered Data Holders
4. Successfully executed DCR
5. Successfully created consent
6. Successfully refreshed tokens
7. Attempted get banking/accounts from Consumer Data Sharing after selecting the created arrangement
8. Error message within swagger execute page
9. Failed to fetch, refer screenshot

**Expected behaviour**
Data should be retrieved for get accounts and shown as a valid response on the page

**Screenshots**
If applicable, add screenshots
![22C274A8-CF41-427F-B075-B56D1CA0461B](https://user-images.githubusercontent.com/93981915/140912414-b889f5cc-bedc-4e18-89c5-b32223c95c85.png)
 to help explain your problem.

**Additional context**

**Comment by CDR-CT** [comment]
Hi @markchan-gits,

Good day!

I need a bit more information to diagnose this issue. Could you please provide your answers to below questions and try out the suggestions below?

1. In the 'Consumer Data Sharing' page, did you select the 'consent' from the drop-down before executing this API?
2. It could also be a local self-signed certificate trust issue. Can you invoke the ../banking/accounts/.. API in your local browser? You won't get a success result by invoking this API in the browser, but it will prompt you to trust the certificate if you already haven't done so.
3. If none of the above work, can you please share the MDR and the MDH logs when this happens?

Regards,
Chris

**Comment by yanhernan** [comment]
Hi, here is the problem:

When the host is assigned to generate swagger.json on the **/data-sharing/swagger** endpoint, the port is not configured, making hostname invalid, therefore all requests for data sharing view will fail

**Fix**
It change the line 72 in file DataSharingController.cs
```
Uri uri = new Uri(sp.RecipientBaseUri);
json["host"] = $"{uri.Host}:{uri.Port}";
```

**Screenshots**
![image](https://user-images.githubusercontent.com/4741345/141830879-e792bd32-6f82-4f6b-b203-75c02cd97ace.png)

**Comment by CDR-AndrewG** [comment]
Thank you for the code snippet. We have added this fix to our local code repo and will include it in our next release. We are currently preparing a release for our Mock Data Holder and will provide a Mock Data Recipient release shortly after.

**Comment by markchan-gits** [comment]
> Hi, here is the problem:
> 
> When the host is assigned to generate swagger.json on the **/data-sharing/swagger** endpoint, the port is not configured, making hostname invalid, therefore all requests for data sharing view will fail
> 
> **Fix** It change the line 72 in file DataSharingController.cs
> 
> ```
> Uri uri = new Uri(sp.RecipientBaseUri);
> json["host"] = $"{uri.Host}:{uri.Port}";
> ```
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/4741345/141830879-e792bd32-6f82-4f6b-b203-75c02cd97ace.png)

Nice find @yanhernan

**Comment by CDR-AndrewG** [comment]
Hi, our release addressing this issue is now available in the develop and main branch.
