### ISSUE TITLE
PKCE support

### ISSUE THREAD

**Issue by ikawalec** [ConsumerDataRight/mock-data-recipient#49]
**Is your feature request related to a problem? Please describe.**

PKCE support is marked as mandatory after the 16th of September:
https://github.com/ConsumerDataStandardsAustralia/standards/issues/209

**Describe the solution you'd like**
Data recipient should support PKCE: https://www.rfc-editor.org/rfc/rfc7636.html

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by CDR-AndrewG** [comment]
Hi @ikawalec,

Thank you for getting in touch and taking the time to raise this request. The mock-data-recipient provides an option for using PKCE in both the Hybrid Flow and the Pushed Authorisation Flow.

A checkbox is included in the PAR screen and Consent and Authorisation screen. The usage can then be seen in the [Consent Controller](https://github.com/ConsumerDataRight/mock-data-recipient/blob/main/Source/CDR.DataRecipient.Web/Controllers/ConsentController.cs) and [PAR Controller](https://github.com/ConsumerDataRight/mock-data-recipient/blob/main/Source/CDR.DataRecipient.Web/Controllers/ParController.cs).

Please let me know if this is what you are looking for or if further functionality is needed.

**Comment by ikawalec** [comment]
Hi,

thanks, I haven't noticed it.
It seems that we are using the older version.

This can be closed.
