### ISSUE TITLE
DCR request contains string instead of array for redirect_uris and response_types fields

### ISSUE THREAD

**Issue by ikawalec** [ConsumerDataRight/mock-data-recipient#50]
**Describe the bug**
When DR makes a DCR request, it sends a string instead of an array for `redirect_uris` and `response_types` fields, for example:

```
{
  ...
  "redirect_uris": "https://dr.cdrsandbox.gov.au/consent/callback",
  "grant_types": [
    "client_credentials",
    "authorization_code",
    "refresh_token"
  ],
  "response_types": "code id_token",
  ...
}
```

**To Reproduce**
Run DR and use Client registration option.

**Expected behaviour**
Even if `redirect_uris` / `response_types` contains a single string, it should send it as one element array as per RFC spec: https://www.rfc-editor.org/rfc/rfc7591.html, for example:

```
{
  ...
  "redirect_uris": [
    "https://dr.cdrsandbox.gov.au/consent/callback"
  ],
  "response_types": [
    "code id_token"
  ]
  ...
}
```

**Screenshots**
n/a

**Additional context**
This issue was spotted when using https://dr.cdrsandbox.gov.au/

**Comment by CDR-AndrewG** [comment]
Hi @ikawalec,

Thank you for getting in touch with us to raise this issue. The information provided and notification of the issue will greatly help to us make the sandbox more closely aligned with the CDR ecosystem.

We have logged the issue and will include a fix in a future release.

**Comment by CDR-AndrewG** [comment]
Hi @ikawalec,

A fix for this issue was released to the [Sandbox](https://cdrsandbox.gov.au/) yesterday.

This issue will be closed after we push the updated code from our internal code repository to this repository.

**Comment by CDR-AndrewG** [comment]
Hi @ikawalec,

The same fix applied to the [sandbox](https://cdrsandbox.gov.au/) is now available in the main branch on this repository.
