### ISSUE TITLE
Mock-Data-Recipient from Ecosystem Compose crashes immediately after starting.

### ISSUE THREAD

**Issue by AngusB-SA** [ConsumerDataRight/mock-data-recipient#52]
**Describe the bug**
When running the Mock CDR ecosystem using the [provided docker-compose file](https://github.com/ConsumerDataRight/mock-register/blob/main/Source/docker-compose.Ecosystem.yml), the `mock-data-recipient` image repeatedly starts and crashes, and is not accessible on port 9001.

**To Reproduce**
Steps to reproduce the behaviour:
1. I am running the containers on a Linux x86_64 machine.
2. Pull the `docker-compose` file linked above onto your machine.
3. Add the needed hosts into the host file; `mock-register`, `mock-data-holder`, `mock-data-holder-energy` and `mock-data-recipient` should all resolve to the equivalent of IPv4 localhost.
4. Spin up the docker images using `docker-compose up -d`.
5. Let them run for a minute or 2 to get started.
6. Inspect the logs of the recipient image; `docker logs mock-data-recipient`
7. If error has occurred, log lines like those shown below will be shown over and over again.

```
CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
INFO supervisord started with pid 1
INFO spawned: 'CDR.DataRecipient.Web' with pid 7
INFO success: CDR.DataRecipient.Web entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
INFO exited: CDR.DataRecipient.Web (exit status 1; not expected)
INFO spawned: 'CDR.DataRecipient.Web' with pid 24
INFO success: CDR.DataRecipient.Web entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
INFO exited: CDR.DataRecipient.Web (exit status 1; not expected)
INFO spawned: 'CDR.DataRecipient.Web' with pid 41
INFO success: CDR.DataRecipient.Web entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
INFO exited: CDR.DataRecipient.Web (exit status 1; not expected)
```

**Expected behaviour**
My expectation was that the service `CDR.DataRecipient.Web` would start and stay up, and would be openable in browser at an address like `https://localhost:9001/`, and should load a page similar to the one in the screenshot at the bottom of the [HELP.md](https://github.com/ConsumerDataRight/mock-data-recipient/blob/main/Help/container/HELP.md) file.

**Comment by AngusB-SA** [comment]
I figured out what the problem is; In the Ecosystem `docker-compose` file, the Mock Recipient image doesn't have an `extra_hosts` section, and as such is missing the line `"host.docker.internal:host-gateway"`. Adding this in fixes the problem.

This fix should be added to the Ecosystem `docker-compose` by maintainers.

**Comment by CDR-AndrewG** [comment]
Hi @AngusB-SA,

Thank you for raising this issue and for providing a fix. It is very much appreciated. The fix will be incorporated in our next release which we are in the process of preparing for deployment.

**Comment by CDR-AndrewG** [comment]
Hi @AngusB-SA,

This issue has been resolved in our latest release.
