### ISSUE TITLE
redirect_uris and response_types in DCR request should be array of string

### ISSUE THREAD

**Issue by Smoovsky** [ConsumerDataRight/mock-data-recipient#59]
**Describe the bug**
```redirect_uris```  and ```response_types``` in DCR request should be array of string but a single string value is passed from mock data recipient.
Sample DCR request from mock data recipient:
```json
{
    // ...
    "authorization_signed_response_alg": "PS256",
    "authorization_encrypted_response_alg": "",
    "authorization_encrypted_response_enc": "",
    // expect string array here but got string
    "redirect_uris": "https://host.docker.internal:9001/consent/callback",
    "grant_types": [
        "client_credentials",
        "authorization_code",
        "refresh_token"
    ],
    // expect string array here but got string
    "response_types": "code id_token",
    "exp": 1681966415,
    "iss": "c6327f87-687a-4369-99a4-eaacd3bb8210",
    "aud": "https://localhost:7132"
}
```

**Comment by CDR-AndrewG** [comment]
Hi @Smoovsky,

Thank you for reaching out. We have logged the issue and will include a fix in a future release.

**Comment by Smoovsky** [comment]
> Hi @Smoovsky,
> 
> Thank you for reaching out. We have logged the issue and will include a fix in a future release.

Hi @CDR-AndrewG ,
There is another thing:  ```authorization_encrypted_response_alg``` and ```authorization_encrypted_response_enc``` are empty strings if they were left blank on mock data recipient's dynamic client registration page. Though it sounds fine data holder should handle them as ```null```, it's still kinda wrong. What would you suggest?

**Comment by CDR-AndrewG** [comment]
Hi @Smoovsky ,

This issue has been resolved and the fix is available in the main branch.
