### ISSUE TITLE
mock data recipient's client certificate expired today (15/06/2023)

### ISSUE THREAD

**Issue by Smoovsky** [ConsumerDataRight/mock-data-recipient#64]

**Comment by CDR-AndrewG** [comment]
Hi @Smoovsky ,

Thank you for contacting us and raising this issue. Apologies for the inconvenience caused. 

We are creating the new certificates now and will publish to GitHub as soon as they are available.

If a workaround is needed until then the below can help:

If you are using the mock-data-recipient and mock-register using visual studio, this [cmd file](https://github.com/ConsumerDataRight/mock-register/blob/main/CertificateManagement/mtls/client.cmd) can regenerate a new client mtls certificate. 

If you do create and use a new certificate, the new certificate's thumbprint would need to be updated in the mock-register database - `cdr-register.dbo.SoftwareProductCertificate.Thumbprint`

To use the mock-data-recipient in a docker container, the new client certificate would need to be used to overwrite the existing certificates in the code base. Then the container needs to be re-built using this [dockerfile](https://github.com/ConsumerDataRight/mock-data-recipient/blob/main/Source/Dockerfile).


We will update this issue as soon as the new certificates are available.

**Comment by CDR-AndrewG** [comment]
Hi @Smoovsky,

All expired certificates have been updated in the [mock-register](https://github.com/ConsumerDataRight/mock-register), [authorisation-server](https://github.com/ConsumerDataRight/authorisation-server), [mock-data-holder](https://github.com/ConsumerDataRight/mock-data-holder), [mock-data-holder-energy](https://github.com/ConsumerDataRight/mock-data-holder-energy) and [mock-data-recipient](https://github.com/ConsumerDataRight/mock-data-recipient) code repositories. 

The latest docker images are available on [Docker Hub](https://hub.docker.com/u/consumerdataright).

**Comment by FiskilBen** [comment]
Hi team, thank you for updating the certificates. I'm no longer getting 500 errors when refreshing data holders from the mock recipient. However, now I'm observing an error returned from the mock-register and the data holders list still won't refresh. The UI shows `BadRequest - {"error":"invalid_client","error_description":"Client certificate validation failed"}`. I'm wondering if there is something wrong with the new certificate(s)?

![image](https://github.com/ConsumerDataRight/mock-data-recipient/assets/134976887/30e190d6-1b71-48a5-aeef-b4218ce9c8c8)
and I can see some errors in the logs too:

```
mock-register            | 04:48:39.174 +00:00 Information [Serilog.AspNetCore.RequestLoggingMiddleware] HTTP "POST" "/idp/connect/token" responded 400 in 2608.1169 ms                                                                                     mock-register            | 04:48:39.178 +00:00 Debug [Microsoft.EntityFrameworkCore.Infrastructure] '"RegisterDatabaseContext"' disposed.
mock-register            | [04:48:39 INF] requestId: 0HMRI2B327KKK:00000002, previousRequestId: no previous request id, message: 400 (Bad Request) status code, request uri: https://localhost:7002/idp/connect/token
mock-register            | [04:48:39 DBG] requestId: 0HMRI2B327KKK:00000002, previousRequestId: no previous request id, message: setting http response message                                                                                              mock-register            | [04:48:39 DBG] requestId: 0HMRI2B327KKK:00000002, previousRequestId: no previous request id, message: no pipeline errors, setting and returning completed response
mock-register            | [04:48:39 DBG] requestId: 0HMRI2B327KKK:00000002, previousRequestId: no previous request id, message: ocelot pipeline finished
mock-data-recipient      | 04:48:39.214 +00:00 Debug [CDR.DataRecipient.SDK.Services.Tokens.AccessTokenService] Access Token Response: BadRequest.  Body: "{\"error\":\"invalid_client\",\"error_description\":\"Client certificate validation failed\"}"
mock-register            | [04:48:39 INF] HTTP POST /idp/connect/token responded 400 in 2884.4236 ms
```

I'm running the services using a derivative of the provided docker compose config

mock-register:1.2
mock-data-holder-energy:1.3
mock-data-recipient:1.2

**Comment by CDR-AndrewG** [comment]
Hi @FiskilBen,

Thank you for bringing this to our attention. We have tried the same scenario and were able to complete the Get Data Holders request without experiencing an issue.

There are a couple of ways this issue could occur:

1. Using an old version of `mock-register:1.2`, `mock-data-holder-energy:1.3` or `mock-data-recipient:1.2` would still have the expired certificate. Can you try deleting your local copies so the latest images are pulled from Docker Hub when using the docker compose.
2. If you are using a persistent database and not one inside the docker image then the `ThumbPrint` in `cdr-register.dbo.SoftwareProductCertificate` need to be updated. The new `Thumbprint` is `f0e5146a51f16e236844cf0353d791f11865e405`.

Let us know if that helps.

**Comment by FiskilBen** [comment]
Thanks for the quick response @CDR-AndrewG. I was using a separate mssql container for the db as shown in the example docker compose config https://github.com/ConsumerDataRight/mock-data-recipient/blob/main/Source/DockerCompose/docker-compose.yml

Connecting to the sql server and updating the thumbprints in the table directly resolved the issue for me. Is there a seed data script that needs to be updated with the latest thumbprints?

For reference here's the query that resolved the issue for me:

```sql
UPDATE [cdr-register].[dbo].[SoftwareProductCertificate]
SET  Thumbprint = 'f0e5146a51f16e236844cf0353d791f11865e405';

```

**Comment by CDR-AndrewG** [comment]
Hi @FiskilBen,

Glad that helped.

The mock-register's [seed-data](https://github.com/ConsumerDataRight/mock-register/blob/main/Source/CDR.Register.Admin.API/Data/seed-data.Release.json) has been updated to include the new Thumbprints.

The seed-data is only used when creating the database for the first time. The database migrations have will change the database structure but not the underlying data.

There are a couple of APIs that can be used to update the data in the mock-register database:

[load-your-own-data-into-the-mock-register](https://github.com/ConsumerDataRight/mock-register#load-your-own-data-into-the-mock-register)

[reate-or-update-data-recipient-records-via-the-admin-api](https://github.com/ConsumerDataRight/mock-register#create-or-update-data-recipient-records-via-the-admin-api)
