### ISSUE TITLE
"IndustryName" validation causing proxy to discovery endpoints failed

### ISSUE THREAD

**Issue by Smoovsky** [ConsumerDataRight/mock-data-recipient#68]
Currently the data recipient's proxy controller expects something like ```/cds-au/v1/common/status```('common' as the industry name), but it should be ```/cds-au/v1/discovery/status```.

**Comment by CDR-AndrewG** [comment]
Hi @Smoovsky,

Thank you for reaching out and raising this issue. We have logged the issue and will include a fix in a future release.

**Comment by CDR-HansenS** [comment]
Hi @Smoovsky ,

Just updating you that this issue has now been fixed in our latest release.

Thanks,
Hansen

**Comment by CDR-HansenS** [comment]
Hi @Smoovsky , just letting you know that this has now been fixed in our latest release today.

Thank you.
